package FrmExpendedora;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import maquinaexpendedora.MaquinaExpendedora;

/*
 * Forma principal que simula la máquina expendedora de refrescos
 */

/**
 *
 * @author JOHDLS
 */
public class FrmInicio extends javax.swing.JFrame {
    
    // instancia que maneja la logica de la máquina expendedora
    private final MaquinaExpendedora maquinaExpendedora;
    
    /**
     * Constructor
     * Crea una nueva instancia de la forma (clase) FrmInicio
     * @throws java.awt.FontFormatException
     * @throws java.io.IOException
     */
    public FrmInicio() throws FontFormatException, IOException {
        initComponents();
        
        //Cargar la fuente espacial para que las letras se vean como de 'vending machine'
        InputStream is = getClass().getResourceAsStream("/fuentes/Digital7-1e1Z.ttf");
        Font fontDigital = Font.createFont(Font.TRUETYPE_FONT, is);
        Font fontDigitalSized = fontDigital.deriveFont(20f);
        //cambiar la fuente de los textos que queremos que se vean como leds
        txtInformacion.setFont(fontDigitalSized);
        txtEfectivo.setFont(fontDigitalSized);
        txtCantidadNormal.setFont(fontDigitalSized);
        txtCantidadCafe.setFont(fontDigitalSized);
        txtCantidadCherry.setFont(fontDigitalSized);
        txtCantidadEnergy.setFont(fontDigitalSized);
        txtCantidadLight.setFont(fontDigitalSized);
        txtCantidadNaranja.setFont(fontDigitalSized);
        txtCantidadSinAzucar.setFont(fontDigitalSized);
        txtCantidadZero.setFont(fontDigitalSized);
        
        // crear la instancia (objeto) de la clase que se encarga de manpular la lógica de la máquina expendedora
        maquinaExpendedora = new MaquinaExpendedora();
        
        actualizarCantidadesProductos();
    }

    private void actualizarCantidadesProductos(){
        txtCantidadCafe.setText("" + maquinaExpendedora.cocaCafe.getDisponible());
        txtCantidadCherry.setText("" + maquinaExpendedora.cocaCherry.getDisponible());
        txtCantidadEnergy.setText("" + maquinaExpendedora.cocaEnergy.getDisponible());
        txtCantidadLight.setText("" + maquinaExpendedora.cocaLight.getDisponible());
        txtCantidadNaranja.setText("" + maquinaExpendedora.cocaNaranja.getDisponible());
        txtCantidadSinAzucar.setText("" + maquinaExpendedora.cocaSinAzucar.getDisponible());
        txtCantidadZero.setText("" + maquinaExpendedora.cocaZero.getDisponible());
        txtCantidadNormal.setText("" + maquinaExpendedora.cocaNormal.getDisponible());
    }
    
    private void productoPresionadoAccion(String producto){
        String msj = maquinaExpendedora.productoPresionado(producto);
        txtInformacion.setText(msj);
        actualizarCantidadesProductos();
        if(msj.contains("Su cambio es: $ ")){
            txtEfectivo.setText("$ 0.00");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField3 = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();
        btnCocaNormal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCocaLight = new javax.swing.JButton();
        btnCocaSinAzucar = new javax.swing.JButton();
        btnCocaZero = new javax.swing.JButton();
        btnCocaCafe = new javax.swing.JButton();
        btnCocaCherry = new javax.swing.JButton();
        btnCocaEnergy = new javax.swing.JButton();
        btnCocaNaranja = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnQuinientos = new javax.swing.JButton();
        btnDoscientos = new javax.swing.JButton();
        btnCien = new javax.swing.JButton();
        btnCincuenta = new javax.swing.JButton();
        btnVeinte = new javax.swing.JButton();
        btnDiez = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        txtEfectivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtInformacion = new javax.swing.JTextField();
        txtCantidadLight = new javax.swing.JTextField();
        txtCantidadNormal = new javax.swing.JTextField();
        txtCantidadZero = new javax.swing.JTextField();
        txtCantidadSinAzucar = new javax.swing.JTextField();
        txtCantidadCafe = new javax.swing.JTextField();
        txtCantidadCherry = new javax.swing.JTextField();
        txtCantidadEnergy = new javax.swing.JTextField();
        txtCantidadNaranja = new javax.swing.JTextField();

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setForeground(new java.awt.Color(51, 255, 51));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("00");
        jTextField3.setBorder(null);
        jTextField3.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        jTextField3.setSelectionColor(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 0, 0));

        btnCocaNormal.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaNormal.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCocaNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca lata.png"))); // NOI18N
        btnCocaNormal.setText("Normal $17.00");
        btnCocaNormal.setToolTipText("");
        btnCocaNormal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaNormal.setName(""); // NOI18N
        btnCocaNormal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaNormalActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca cola banner.png"))); // NOI18N

        btnCocaLight.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaLight.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCocaLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca light.png"))); // NOI18N
        btnCocaLight.setText("Light $17.00");
        btnCocaLight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaLight.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaLightActionPerformed(evt);
            }
        });

        btnCocaSinAzucar.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaSinAzucar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCocaSinAzucar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca sin azucar.png"))); // NOI18N
        btnCocaSinAzucar.setText("Sin Azúcar $17.00");
        btnCocaSinAzucar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaSinAzucar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnCocaSinAzucar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaSinAzucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaSinAzucarActionPerformed(evt);
            }
        });

        btnCocaZero.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaZero.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCocaZero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca zero.png"))); // NOI18N
        btnCocaZero.setText("Zero $17.00");
        btnCocaZero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaZero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaZeroActionPerformed(evt);
            }
        });

        btnCocaCafe.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaCafe.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCocaCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca cafe.png"))); // NOI18N
        btnCocaCafe.setText("Café $17.00");
        btnCocaCafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaCafe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaCafeActionPerformed(evt);
            }
        });

        btnCocaCherry.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaCherry.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCocaCherry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca cherry.png"))); // NOI18N
        btnCocaCherry.setText("Cherry $17.00");
        btnCocaCherry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaCherry.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaCherry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaCherryActionPerformed(evt);
            }
        });

        btnCocaEnergy.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaEnergy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCocaEnergy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca energy.png"))); // NOI18N
        btnCocaEnergy.setText("Energy $17.00");
        btnCocaEnergy.setToolTipText("");
        btnCocaEnergy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaEnergy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaEnergyActionPerformed(evt);
            }
        });

        btnCocaNaranja.setBackground(new java.awt.Color(255, 255, 255));
        btnCocaNaranja.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCocaNaranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coca vainilla.png"))); // NOI18N
        btnCocaNaranja.setText("Naranja $17.00");
        btnCocaNaranja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocaNaranja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCocaNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocaNaranjaActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 255, 255));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setToolTipText("");
        lblResultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnQuinientos.setText("$500");
        btnQuinientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuinientosActionPerformed(evt);
            }
        });

        btnDoscientos.setText("$200");
        btnDoscientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoscientosActionPerformed(evt);
            }
        });

        btnCien.setText("$100");
        btnCien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCienActionPerformed(evt);
            }
        });

        btnCincuenta.setText("$50");
        btnCincuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincuentaActionPerformed(evt);
            }
        });

        btnVeinte.setText("$20");
        btnVeinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeinteActionPerformed(evt);
            }
        });

        btnDiez.setText("$10");
        btnDiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiezActionPerformed(evt);
            }
        });

        btnCinco.setText("$5");
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnDos.setText("$2");
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });

        btnUno.setText("$1");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        txtEfectivo.setEditable(false);
        txtEfectivo.setBackground(new java.awt.Color(0, 0, 0));
        txtEfectivo.setForeground(new java.awt.Color(51, 255, 51));
        txtEfectivo.setText("$0.00");
        txtEfectivo.setAutoscrolls(false);
        txtEfectivo.setMargin(new java.awt.Insets(0, 2, 2, 2));
        txtEfectivo.setPreferredSize(new java.awt.Dimension(33, 20));
        txtEfectivo.setSelectedTextColor(new java.awt.Color(51, 255, 51));
        txtEfectivo.setSelectionColor(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Efectivo");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Introducido:");

        btnCancelar.setText("Cancelar");
        btnCancelar.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5pesos-small.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/10pesos_small.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1peso-small.png"))); // NOI18N
        jLabel8.setText("jLabel2");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2pesos-small.png"))); // NOI18N
        jLabel9.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/500pesos-small.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/200pesos-small.jpg"))); // NOI18N
        jLabel7.setText("jLabel3");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/100pesos-small.jpg"))); // NOI18N
        jLabel10.setText("jLabel3");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/50pesos-small.jpg"))); // NOI18N
        jLabel11.setText("jLabel3");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/20pesos-small.jpg"))); // NOI18N
        jLabel12.setText("jLabel3");

        jButton1.setText("Inventario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnQuinientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDoscientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVeinte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDiez)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDiez)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCinco)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDos)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnUno)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnQuinientos)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnDoscientos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnCien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(btnCincuenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(btnVeinte))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        txtInformacion.setEditable(false);
        txtInformacion.setBackground(new java.awt.Color(0, 0, 0));
        txtInformacion.setForeground(new java.awt.Color(51, 255, 51));
        txtInformacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInformacion.setText("BIENVENIDO!");
        txtInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtInformacion.setName("informacionText"); // NOI18N
        txtInformacion.setSelectedTextColor(new java.awt.Color(102, 255, 0));
        txtInformacion.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtCantidadLight.setEditable(false);
        txtCantidadLight.setBackground(new java.awt.Color(0, 0, 0));
        txtCantidadLight.setForeground(new java.awt.Color(51, 255, 51));
        txtCantidadLight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadLight.setText("00");
        txtCantidadLight.setBorder(null);
        txtCantidadLight.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        txtCantidadLight.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtCantidadNormal.setEditable(false);
        txtCantidadNormal.setBackground(new java.awt.Color(0, 0, 0));
        txtCantidadNormal.setForeground(new java.awt.Color(51, 255, 51));
        txtCantidadNormal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadNormal.setText("00");
        txtCantidadNormal.setBorder(null);
        txtCantidadNormal.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        txtCantidadNormal.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtCantidadZero.setEditable(false);
        txtCantidadZero.setBackground(new java.awt.Color(0, 0, 0));
        txtCantidadZero.setForeground(new java.awt.Color(51, 255, 51));
        txtCantidadZero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadZero.setText("00");
        txtCantidadZero.setBorder(null);
        txtCantidadZero.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        txtCantidadZero.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtCantidadSinAzucar.setEditable(false);
        txtCantidadSinAzucar.setBackground(new java.awt.Color(0, 0, 0));
        txtCantidadSinAzucar.setForeground(new java.awt.Color(51, 255, 51));
        txtCantidadSinAzucar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadSinAzucar.setText("00");
        txtCantidadSinAzucar.setBorder(null);
        txtCantidadSinAzucar.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        txtCantidadSinAzucar.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtCantidadCafe.setEditable(false);
        txtCantidadCafe.setBackground(new java.awt.Color(0, 0, 0));
        txtCantidadCafe.setForeground(new java.awt.Color(51, 255, 51));
        txtCantidadCafe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadCafe.setText("00");
        txtCantidadCafe.setBorder(null);
        txtCantidadCafe.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        txtCantidadCafe.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtCantidadCherry.setEditable(false);
        txtCantidadCherry.setBackground(new java.awt.Color(0, 0, 0));
        txtCantidadCherry.setForeground(new java.awt.Color(51, 255, 51));
        txtCantidadCherry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadCherry.setText("00");
        txtCantidadCherry.setBorder(null);
        txtCantidadCherry.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        txtCantidadCherry.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtCantidadEnergy.setEditable(false);
        txtCantidadEnergy.setBackground(new java.awt.Color(0, 0, 0));
        txtCantidadEnergy.setForeground(new java.awt.Color(51, 255, 51));
        txtCantidadEnergy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadEnergy.setText("00");
        txtCantidadEnergy.setBorder(null);
        txtCantidadEnergy.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        txtCantidadEnergy.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtCantidadNaranja.setEditable(false);
        txtCantidadNaranja.setBackground(new java.awt.Color(0, 0, 0));
        txtCantidadNaranja.setForeground(new java.awt.Color(51, 255, 51));
        txtCantidadNaranja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadNaranja.setText("00");
        txtCantidadNaranja.setBorder(null);
        txtCantidadNaranja.setSelectedTextColor(new java.awt.Color(0, 255, 0));
        txtCantidadNaranja.setSelectionColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lblResultado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCocaNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCocaCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtCantidadNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtCantidadCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCocaCherry, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCocaLight, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtCantidadLight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtCantidadCherry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCocaEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCocaSinAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtCantidadSinAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtCantidadEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCocaNaranja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCocaZero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadZero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnCocaLight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadLight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnCocaNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnCocaSinAzucar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadSinAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnCocaZero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadZero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCocaCafe)
                    .addComponent(btnCocaCherry)
                    .addComponent(btnCocaEnergy)
                    .addComponent(btnCocaNaranja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidadCherry, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultado)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, maquinaExpendedora.getInventario(), "Inventario", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCocaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaNormalActionPerformed
        productoPresionadoAccion("Coca Normal");
    }//GEN-LAST:event_btnCocaNormalActionPerformed

    private void btnCocaLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaLightActionPerformed
        productoPresionadoAccion("Coca Light");
    }//GEN-LAST:event_btnCocaLightActionPerformed

    private void btnCocaSinAzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaSinAzucarActionPerformed
       productoPresionadoAccion("Coca Sin Azucar");
    }//GEN-LAST:event_btnCocaSinAzucarActionPerformed

    private void btnCocaZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaZeroActionPerformed
        productoPresionadoAccion("Coca Zero");
    }//GEN-LAST:event_btnCocaZeroActionPerformed

    private void btnCocaCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaCafeActionPerformed
        productoPresionadoAccion("Coca Cafe");
    }//GEN-LAST:event_btnCocaCafeActionPerformed

    private void btnCocaCherryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaCherryActionPerformed
        productoPresionadoAccion("Coca Cherry");
    }//GEN-LAST:event_btnCocaCherryActionPerformed

    private void btnCocaEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaEnergyActionPerformed
        productoPresionadoAccion("Coca Energy");
    }//GEN-LAST:event_btnCocaEnergyActionPerformed

    private void btnCocaNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocaNaranjaActionPerformed
        productoPresionadoAccion("Coca Naranja");
    }//GEN-LAST:event_btnCocaNaranjaActionPerformed

    private void btnQuinientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuinientosActionPerformed
        dineroPresionadoAccion("500");
    }//GEN-LAST:event_btnQuinientosActionPerformed

    private void btnDoscientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoscientosActionPerformed
        dineroPresionadoAccion("200");
    }//GEN-LAST:event_btnDoscientosActionPerformed

    private void btnCienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCienActionPerformed
        dineroPresionadoAccion("100");
    }//GEN-LAST:event_btnCienActionPerformed

    private void btnCincuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincuentaActionPerformed
        dineroPresionadoAccion("50");
    }//GEN-LAST:event_btnCincuentaActionPerformed

    private void btnVeinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeinteActionPerformed
        dineroPresionadoAccion("20");
    }//GEN-LAST:event_btnVeinteActionPerformed

    private void btnDiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiezActionPerformed
        dineroPresionadoAccion("10");
    }//GEN-LAST:event_btnDiezActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        dineroPresionadoAccion("5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        dineroPresionadoAccion("2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        dineroPresionadoAccion("1");
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtEfectivo.setText("$ 0.00");
        txtInformacion.setText("Recoja su dinero");
        maquinaExpendedora.cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void dineroPresionadoAccion(String monto){
        String msj = maquinaExpendedora.dineroPresionado(monto);
        if("No se puede aceptar".equals(msj)){
            txtInformacion.setText(msj);
        } else {
            txtEfectivo.setText(maquinaExpendedora.getEfectivoIntroducido());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Crear y mostrar la forma */
        java.awt.EventQueue.invokeLater(() -> {  //usando notacion lambda
            try {
                new FrmInicio().setVisible(true);
            } catch (FontFormatException | IOException ex) {
                Logger.getLogger(FrmInicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCien;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCincuenta;
    private javax.swing.JButton btnCocaCafe;
    private javax.swing.JButton btnCocaCherry;
    private javax.swing.JButton btnCocaEnergy;
    private javax.swing.JButton btnCocaLight;
    private javax.swing.JButton btnCocaNaranja;
    private javax.swing.JButton btnCocaNormal;
    private javax.swing.JButton btnCocaSinAzucar;
    private javax.swing.JButton btnCocaZero;
    private javax.swing.JButton btnDiez;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnDoscientos;
    private javax.swing.JButton btnQuinientos;
    private javax.swing.JButton btnUno;
    private javax.swing.JButton btnVeinte;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtCantidadCafe;
    private javax.swing.JTextField txtCantidadCherry;
    private javax.swing.JTextField txtCantidadEnergy;
    private javax.swing.JTextField txtCantidadLight;
    private javax.swing.JTextField txtCantidadNaranja;
    private javax.swing.JTextField txtCantidadNormal;
    private javax.swing.JTextField txtCantidadSinAzucar;
    private javax.swing.JTextField txtCantidadZero;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtInformacion;
    // End of variables declaration//GEN-END:variables
}
